[project]
name = "robot-stack"
version = "0.1.0"
description = "Tools to inspect and build Opentrons robots"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "rich>=14.0.0",
    "ruff>=0.11.5",
    "rust-just>=1.40.0",
    "semver>=3.0.4",
]

[tool.black]
line-length = 130

[tool.ruff]
line-length = 130
